import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";

import "leaflet/dist/leaflet.css";
import "leaflet.markercluster/dist/MarkerCluster.css";
import "leaflet.markercluster/dist/MarkerCluster.Default.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <div className="flex h-screen w-full overflow-hidden bg-military-black text-slate-200 font-sans">
          <SideBar />
          <main className="flex-1 flex flex-col overflow-hidden relative">
            <div className="absolute inset-0 tactical-grid opacity-50 pointer-events-none" />
            <Header />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
